MAX_EPOCHS: 20
SAMP_RATE: 200
batch_size: 64
class_labels:
- NoN-Ripple
- Ripple
d_ratio1: 0.85
d_ratio2: 0.85
device_index: 0
device_type: cuda
do_under_sampling: true
dtype: fp32
is_debug_mode: false
lr: 0.001
montage:
- F3
- F4
- C3
- C4
- O1
- O2
n_fc1: 1024
n_fc2: 256
n_gpus: 1
n_repeat: 5
n_subjs_tra: 3
num_workers: 20
random_state: 42
sdir: /home/ywatanabe/proj/human_ripple_EEG/train/MNet/ywatanabe/NoN-Ripple_vs_Ripple/_MNet_100_WindowSize-0.5-sec_MaxEpochs_20_2022-1101-1852/seg-level/
tau_ms: 0
tes_ratio: 0.333
val_ratio: 0.333
window_size_pts: 100
window_size_sec: 0.5
ws_pts: 100
