random_state:
    42
    
batch_size:
  # 128
  # 512
  32

# max_n_EEGs_per_sub:
#   100

is_debug_mode:
  False

is_random_init:
  False

transform:
  False

num_workers:
  2
  # 24

class_field_name:
    disease_type

dtype:
  fp32
